#!/bin/bash

if [ $# -ne 1 ]
then
	echo -e "\033[1;31mUSAGE: $0 <on|off>\033[0m"
	exit 1
fi

SCR=1

case "$1" in

on)
echo "Switching on the Rift..."
xrandr --screen $SCR --output HDMI-0 --auto
;;

off)
echo "Switching off the Rift..."
xrandr --screen $SCR --output HDMI-0 --off
;;

*)
echo "USAGE: $0 <on|off>"
exit 1
;;
esac
